#######################
# Theme Customization #
#######################

title: chenfeng                             # used in <title> tag & site header
author: 魏辰峰                       # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Talk is cheap, show me the code.
slogan: wei                         # used in site header, beside title
avatar: /i/avatar.jpg                       # used as portrait in site header
banner: /i/bg.jpeg                           # used as background in site header
url:              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/vincentweikey # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/vincentweikey
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: chenfengwei2yc       # you know, to protect you from bots. (handle and domain
    domain: gmail.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: NUll
    teaser: 
    url: 
    role: Creator
    category: 

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
